# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PdVisualization.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1067, 706)
        mainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 371, 621))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(30, 100, 311, 271))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_3.setGeometry(QtCore.QRect(30, 470, 311, 121))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 400, 251, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 420, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_4 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout.addWidget(self.toolButton_4)
        self.toolButton_5 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout.addWidget(self.toolButton_5)
        self.toolButton_6 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout.addWidget(self.toolButton_6)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(290, 400, 59, 16))
        self.label.setObjectName("label")
        self.patient_btn = QtWidgets.QPushButton(self.groupBox)
        self.patient_btn.setGeometry(QtCore.QRect(280, 40, 61, 31))
        self.patient_btn.setObjectName("patient_btn")
        self.patient_file = QtWidgets.QPlainTextEdit(self.groupBox)
        self.patient_file.setEnabled(True)
        self.patient_file.setGeometry(QtCore.QRect(30, 40, 241, 31))
        self.patient_file.setLineWidth(1)
        self.patient_file.setMidLineWidth(0)
        self.patient_file.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.patient_file.setCenterOnScroll(True)
        self.patient_file.setObjectName("patient_file")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 0, 371, 621))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(30, 100, 311, 271))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(30, 470, 311, 121))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(30, 400, 251, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 420, 311, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_7 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_2.addWidget(self.toolButton_7)
        self.toolButton_8 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_2.addWidget(self.toolButton_8)
        self.toolButton_9 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_9.setObjectName("toolButton_9")
        self.horizontalLayout_2.addWidget(self.toolButton_9)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(290, 400, 59, 16))
        self.label_2.setObjectName("label_2")
        self.HC_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.HC_btn.setGeometry(QtCore.QRect(280, 40, 61, 31))
        self.HC_btn.setObjectName("HC_btn")
        self.HC_file = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.HC_file.setEnabled(True)
        self.HC_file.setGeometry(QtCore.QRect(30, 40, 241, 31))
        self.HC_file.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.HC_file.setObjectName("HC_file")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(810, 0, 201, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 119, 191, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 27))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "PD Walking Pattern Visualization"))
        self.groupBox.setTitle(_translate("mainWindow", "Patient"))
        self.toolButton_4.setText(_translate("mainWindow", "<<<"))
        self.toolButton_5.setText(_translate("mainWindow", "o"))
        self.toolButton_6.setText(_translate("mainWindow", ">>>"))
        self.label.setText(_translate("mainWindow", "Timer"))
        self.patient_btn.setText(_translate("mainWindow", "Browse"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Health Control"))
        self.toolButton_7.setText(_translate("mainWindow", "<<<"))
        self.toolButton_8.setText(_translate("mainWindow", "o"))
        self.toolButton_9.setText(_translate("mainWindow", ">>>"))
        self.label_2.setText(_translate("mainWindow", "Timer"))
        self.HC_btn.setText(_translate("mainWindow", "Browse"))
        self.groupBox_3.setTitle(_translate("mainWindow", "GroupBox"))
        self.pushButton_4.setText(_translate("mainWindow", "X axis"))
        self.pushButton_3.setText(_translate("mainWindow", "Y axis"))
        self.pushButton_2.setText(_translate("mainWindow", "Z axis"))
        self.pushButton.setText(_translate("mainWindow", "Start Visualization"))
