# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PdVisualization.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1237, 752)
        mainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 481, 711))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(20, 40, 441, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_3.setGeometry(QtCore.QRect(20, 420, 441, 271))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 350, 461, 71))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 10, 351, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(390, 10, 59, 16))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_6 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout.addWidget(self.toolButton_6)
        self.toolButton_5 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout.addWidget(self.toolButton_5)
        self.toolButton_4 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout.addWidget(self.toolButton_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 0, 461, 711))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 40, 421, 311))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(20, 420, 421, 271))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setGeometry(QtCore.QRect(0, 350, 461, 71))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_12)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(30, 10, 351, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_12)
        self.label_13.setGeometry(QtCore.QRect(390, 10, 59, 16))
        self.label_13.setObjectName("label_13")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_12)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(60, 30, 311, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_10 = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_4.addWidget(self.toolButton_10)
        self.toolButton_11 = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_4.addWidget(self.toolButton_11)
        self.toolButton_12 = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_4.addWidget(self.toolButton_12)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(960, -20, 271, 731))
        font = QtGui.QFont()
        font.setFamily("Times")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 200, 271, 231))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 271, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.label_3.setObjectName("label_3")
        self.entry_flist_1 = QtWidgets.QPlainTextEdit(self.groupBox_7)
        self.entry_flist_1.setEnabled(True)
        self.entry_flist_1.setGeometry(QtCore.QRect(60, 20, 171, 31))
        self.entry_flist_1.setLineWidth(1)
        self.entry_flist_1.setMidLineWidth(0)
        self.entry_flist_1.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_1.setCenterOnScroll(True)
        self.entry_flist_1.setObjectName("entry_flist_1")
        self.btn_flist_1 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_flist_1.setGeometry(QtCore.QRect(230, 20, 31, 31))
        self.btn_flist_1.setObjectName("btn_flist_1")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 61, 20))
        self.label_5.setObjectName("label_5")
        self.entry_flist_2 = QtWidgets.QPlainTextEdit(self.groupBox_7)
        self.entry_flist_2.setEnabled(True)
        self.entry_flist_2.setGeometry(QtCore.QRect(60, 60, 171, 31))
        self.entry_flist_2.setLineWidth(1)
        self.entry_flist_2.setMidLineWidth(0)
        self.entry_flist_2.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_2.setCenterOnScroll(True)
        self.entry_flist_2.setObjectName("entry_flist_2")
        self.btn_flist_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_flist_2.setGeometry(QtCore.QRect(230, 60, 31, 31))
        self.btn_flist_2.setObjectName("btn_flist_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 100, 271, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entry_flist_3 = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.entry_flist_3.setEnabled(True)
        self.entry_flist_3.setGeometry(QtCore.QRect(60, 20, 171, 31))
        self.entry_flist_3.setLineWidth(1)
        self.entry_flist_3.setMidLineWidth(0)
        self.entry_flist_3.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_3.setCenterOnScroll(True)
        self.entry_flist_3.setObjectName("entry_flist_3")
        self.btn_flist_3 = QtWidgets.QPushButton(self.groupBox_8)
        self.btn_flist_3.setGeometry(QtCore.QRect(230, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setBold(True)
        font.setWeight(75)
        self.btn_flist_3.setFont(font)
        self.btn_flist_3.setObjectName("btn_flist_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.entry_flist_4 = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.entry_flist_4.setEnabled(True)
        self.entry_flist_4.setGeometry(QtCore.QRect(60, 60, 171, 31))
        self.entry_flist_4.setLineWidth(1)
        self.entry_flist_4.setMidLineWidth(0)
        self.entry_flist_4.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_4.setCenterOnScroll(True)
        self.entry_flist_4.setObjectName("entry_flist_4")
        self.btn_flist_4 = QtWidgets.QPushButton(self.groupBox_8)
        self.btn_flist_4.setGeometry(QtCore.QRect(230, 60, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setBold(True)
        font.setWeight(75)
        self.btn_flist_4.setFont(font)
        self.btn_flist_4.setObjectName("btn_flist_4")
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 20, 271, 131))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 271, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_Xaxis = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_Xaxis.setObjectName("btn_Xaxis")
        self.horizontalLayout_3.addWidget(self.btn_Xaxis)
        self.btn_Yaxis = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_Yaxis.setObjectName("btn_Yaxis")
        self.horizontalLayout_3.addWidget(self.btn_Yaxis)
        self.btn_Zaxis = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_Zaxis.setObjectName("btn_Zaxis")
        self.horizontalLayout_3.addWidget(self.btn_Zaxis)
        self.btn_start = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_start.setGeometry(QtCore.QRect(0, 90, 271, 32))
        self.btn_start.setObjectName("btn_start")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 500, 271, 231))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 19, 271, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_10)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_10)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 61, 20))
        self.label_10.setObjectName("label_10")
        self.entry_flist_6 = QtWidgets.QPlainTextEdit(self.groupBox_10)
        self.entry_flist_6.setEnabled(True)
        self.entry_flist_6.setGeometry(QtCore.QRect(60, 60, 171, 31))
        self.entry_flist_6.setLineWidth(1)
        self.entry_flist_6.setMidLineWidth(0)
        self.entry_flist_6.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_6.setCenterOnScroll(True)
        self.entry_flist_6.setObjectName("entry_flist_6")
        self.btn_flist_6 = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_flist_6.setGeometry(QtCore.QRect(230, 60, 31, 31))
        self.btn_flist_6.setObjectName("btn_flist_6")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 100, 271, 111))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_11)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.label_11.setObjectName("label_11")
        self.entry_flist_7 = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.entry_flist_7.setEnabled(True)
        self.entry_flist_7.setGeometry(QtCore.QRect(60, 20, 171, 31))
        self.entry_flist_7.setLineWidth(1)
        self.entry_flist_7.setMidLineWidth(0)
        self.entry_flist_7.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_7.setCenterOnScroll(True)
        self.entry_flist_7.setObjectName("entry_flist_7")
        self.btn_flist_7 = QtWidgets.QPushButton(self.groupBox_11)
        self.btn_flist_7.setGeometry(QtCore.QRect(230, 20, 31, 31))
        self.btn_flist_7.setObjectName("btn_flist_7")
        self.label_12 = QtWidgets.QLabel(self.groupBox_11)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 61, 20))
        self.label_12.setObjectName("label_12")
        self.entry_flist_8 = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.entry_flist_8.setEnabled(True)
        self.entry_flist_8.setGeometry(QtCore.QRect(60, 60, 171, 31))
        self.entry_flist_8.setLineWidth(1)
        self.entry_flist_8.setMidLineWidth(0)
        self.entry_flist_8.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_8.setCenterOnScroll(True)
        self.entry_flist_8.setObjectName("entry_flist_8")
        self.btn_flist_8 = QtWidgets.QPushButton(self.groupBox_11)
        self.btn_flist_8.setGeometry(QtCore.QRect(230, 60, 31, 31))
        self.btn_flist_8.setObjectName("btn_flist_8")
        self.entry_flist_5 = QtWidgets.QPlainTextEdit(self.groupBox_10)
        self.entry_flist_5.setEnabled(True)
        self.entry_flist_5.setGeometry(QtCore.QRect(60, 20, 171, 31))
        self.entry_flist_5.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_5.setObjectName("entry_flist_5")
        self.btn_flist_5 = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_flist_5.setGeometry(QtCore.QRect(230, 20, 31, 31))
        self.btn_flist_5.setObjectName("btn_flist_5")
        self.verticalLayout_2.addWidget(self.groupBox_10)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1237, 22))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "PD Walking Pattern Visualization"))
        self.groupBox.setTitle(_translate("mainWindow", "Patient"))
        self.label.setText(_translate("mainWindow", "Timer"))
        self.toolButton_6.setText(_translate("mainWindow", ">>>"))
        self.toolButton_5.setText(_translate("mainWindow", "o"))
        self.toolButton_4.setText(_translate("mainWindow", "<<<"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Health Control"))
        self.label_13.setText(_translate("mainWindow", "Timer"))
        self.toolButton_10.setText(_translate("mainWindow", ">>>"))
        self.toolButton_11.setText(_translate("mainWindow", "o"))
        self.toolButton_12.setText(_translate("mainWindow", "<<<"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Operating Panel"))
        self.groupBox_4.setTitle(_translate("mainWindow", "Signal Input — Patient"))
        self.groupBox_7.setTitle(_translate("mainWindow", "Position"))
        self.label_3.setText(_translate("mainWindow", "Left："))
        self.btn_flist_1.setText(_translate("mainWindow", "..."))
        self.label_5.setText(_translate("mainWindow", "Right："))
        self.btn_flist_2.setText(_translate("mainWindow", "..."))
        self.groupBox_8.setTitle(_translate("mainWindow", "Acceleration"))
        self.label_4.setText(_translate("mainWindow", "Left："))
        self.btn_flist_3.setText(_translate("mainWindow", "..."))
        self.label_6.setText(_translate("mainWindow", "Right："))
        self.btn_flist_4.setText(_translate("mainWindow", "..."))
        self.groupBox_6.setTitle(_translate("mainWindow", "View"))
        self.btn_Xaxis.setText(_translate("mainWindow", "X axis"))
        self.btn_Yaxis.setText(_translate("mainWindow", "Y axis"))
        self.btn_Zaxis.setText(_translate("mainWindow", "Z axis"))
        self.btn_start.setText(_translate("mainWindow", "Start Visualization"))
        self.groupBox_9.setTitle(_translate("mainWindow", "Signal Input — Health Control"))
        self.groupBox_10.setTitle(_translate("mainWindow", "Position"))
        self.label_9.setText(_translate("mainWindow", "Left："))
        self.label_10.setText(_translate("mainWindow", "Right："))
        self.btn_flist_6.setText(_translate("mainWindow", "..."))
        self.groupBox_11.setTitle(_translate("mainWindow", "Acceleration"))
        self.label_11.setText(_translate("mainWindow", "Left："))
        self.btn_flist_7.setText(_translate("mainWindow", "..."))
        self.label_12.setText(_translate("mainWindow", "Right："))
        self.btn_flist_8.setText(_translate("mainWindow", "..."))
        self.btn_flist_5.setText(_translate("mainWindow", "..."))

