# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PdVisualization.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1237, 752)
        mainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 551, 711))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(20, 90, 511, 361))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_3.setGeometry(QtCore.QRect(20, 520, 511, 171))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 450, 511, 71))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 10, 421, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(450, 10, 59, 16))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 30, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_pauseLeft = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_pauseLeft.setObjectName("toolButton_pauseLeft")
        self.horizontalLayout.addWidget(self.toolButton_pauseLeft)
        self.toolButton_pause = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_pause.setObjectName("toolButton_pause")
        self.horizontalLayout.addWidget(self.toolButton_pause)
        self.toolButton_pauseRight = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_pauseRight.setObjectName("toolButton_pauseRight")
        self.horizontalLayout.addWidget(self.toolButton_pauseRight)
        self.entry_flist_1 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.entry_flist_1.setEnabled(True)
        self.entry_flist_1.setGeometry(QtCore.QRect(20, 30, 481, 31))
        self.entry_flist_1.setLineWidth(1)
        self.entry_flist_1.setMidLineWidth(0)
        self.entry_flist_1.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_1.setCenterOnScroll(True)
        self.entry_flist_1.setObjectName("entry_flist_1")
        self.btn_flist_1 = QtWidgets.QPushButton(self.groupBox)
        self.btn_flist_1.setGeometry(QtCore.QRect(500, 30, 31, 31))
        self.btn_flist_1.setObjectName("btn_flist_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 0, 531, 711))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 90, 491, 361))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(20, 520, 491, 171))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 450, 491, 71))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalSlider_HC = QtWidgets.QSlider(self.groupBox_12)
        self.horizontalSlider_HC.setGeometry(QtCore.QRect(20, 10, 401, 22))
        self.horizontalSlider_HC.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_HC.setObjectName("horizontalSlider_HC")
        self.label_13 = QtWidgets.QLabel(self.groupBox_12)
        self.label_13.setGeometry(QtCore.QRect(430, 10, 59, 16))
        self.label_13.setObjectName("label_13")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_12)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(90, 30, 311, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_pauseLeft_HC = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.toolButton_pauseLeft_HC.setObjectName("toolButton_pauseLeft_HC")
        self.horizontalLayout_4.addWidget(self.toolButton_pauseLeft_HC)
        self.toolButton_pause_HC = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.toolButton_pause_HC.setObjectName("toolButton_pause_HC")
        self.horizontalLayout_4.addWidget(self.toolButton_pause_HC)
        self.toolButton_pauseRight_HC = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.toolButton_pauseRight_HC.setObjectName("toolButton_pauseRight_HC")
        self.horizontalLayout_4.addWidget(self.toolButton_pauseRight_HC)
        self.entry_flist_5 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.entry_flist_5.setEnabled(True)
        self.entry_flist_5.setGeometry(QtCore.QRect(20, 30, 461, 31))
        self.entry_flist_5.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.entry_flist_5.setObjectName("entry_flist_5")
        self.btn_flist_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_flist_5.setGeometry(QtCore.QRect(480, 30, 31, 31))
        self.btn_flist_5.setObjectName("btn_flist_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(1080, 0, 151, 711))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_start = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_start.setGeometry(QtCore.QRect(0, 570, 151, 71))
        self.btn_start.setObjectName("btn_start")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 120, 151, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 151, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Xaxis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Xaxis.setObjectName("btn_Xaxis")
        self.verticalLayout.addWidget(self.btn_Xaxis)
        self.btn_Yaxis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Yaxis.setObjectName("btn_Yaxis")
        self.verticalLayout.addWidget(self.btn_Yaxis)
        self.btn_Zaxis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Zaxis.setObjectName("btn_Zaxis")
        self.verticalLayout.addWidget(self.btn_Zaxis)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1237, 22))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "PD Walking Pattern Visualization"))
        self.groupBox.setTitle(_translate("mainWindow", "Patient"))
        self.label.setText(_translate("mainWindow", "Timer"))
        self.toolButton_pauseLeft.setText(_translate("mainWindow", "<<<"))
        self.toolButton_pause.setText(_translate("mainWindow", "o"))
        self.toolButton_pauseRight.setText(_translate("mainWindow", ">>>"))
        self.btn_flist_1.setText(_translate("mainWindow", "..."))
        self.groupBox_2.setTitle(_translate("mainWindow", "Health Control"))
        self.label_13.setText(_translate("mainWindow", "Timer"))
        self.toolButton_pauseLeft_HC.setText(_translate("mainWindow", "<<<"))
        self.toolButton_pause_HC.setText(_translate("mainWindow", "o"))
        self.toolButton_pauseRight_HC.setText(_translate("mainWindow", ">>>"))
        self.btn_flist_5.setText(_translate("mainWindow", "..."))
        self.groupBox_3.setTitle(_translate("mainWindow", "Operating Panel"))
        self.btn_start.setText(_translate("mainWindow", "Start Visualization"))
        self.groupBox_4.setTitle(_translate("mainWindow", "Animation View"))
        self.btn_Xaxis.setText(_translate("mainWindow", "X axis"))
        self.btn_Yaxis.setText(_translate("mainWindow", "Y axis"))
        self.btn_Zaxis.setText(_translate("mainWindow", "Z axis"))

